version: 2.1

orbs:
  node: circleci/node@5.2.0

jobs:
  checkoutEtTests:
    docker:
      - image: cimg/node:14.17.0
    steps:
      - run:
          name: Clone backend repository and run tests
          command: |
            git clone https://github.com/emifuge/labo2-backend.git 
            cd labo2-backend && npm install
            cd labo2-backend && npm test

  integrationFrontend:
    docker:
      - image: cimg/node:14.17.0
    steps:
      - run:
          name: Clone frontend and backend repositories
          command: |
            git clone https://github.com/emifuge/labo2-frontend.git && 
            git clone https://github.com/emifuge/labo2-backend.git
      - run:
          name: Install frontend dependencies and build
          command: |
            cd labo2-frontend/3w5-h24-tp2-frontend && npm install 
            cd labo2-frontend/3w5-h24-tp2-frontend && npm run build
      - run:
          name: Prepare backend and copy build from frontend
          command: |
            mkdir -p labo2-backend/3w5-h24-tp2-backend/public && cp -rT labo2-frontend/3w5-h24-tp2-frontend/build labo2-backend/3w5-h24-tp2-backend/public
      - persist_to_workspace:
          root: .
          paths:
            - labo2-backend

  deploiement:
    docker:
      - image: cimg/node:14.17.0
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Show directory structure as if ready for AWS deployment
          command: ls -Rl

workflows:
  build_and_deploy:
    jobs:
      - checkoutEtTests
      - integrationFrontend:
          requires:
            - checkoutEtTests
      - deploiement:
          requires:
            - integrationFrontend
