version: 2.1

orbs:
  node: circleci/node@5.2.0

jobs:
  checkoutEtTests:
    docker:
      - image: cimg/node:20.8.1
    steps:
      - run: git clone https://github.com/emifuge/labo2-backend.git
      - run: cd labo2-backend && npm install
      - run: cd labo2-backend && npm test

  integrationFrontend:
    docker:
      - image: cimg/node:20.8.1
    steps:
      - run: git clone https://github.com/emifuge/labo2-frontend.git && git clone https://github.com/emifuge/labo2-backend.git
      - run: cd labo2-frontend/3w5-h24-tp2-frontend && npm install
      - run: cd labo2-frontend/3w5-h24-tp2-frontend && npm run build
      - run: mkdir -p labo2-backend/public && cp -rT labo2-frontend/build labo2-backend/public
      - persist_to_workspace:
          root: .
          paths:
            - labo2-backend

  deploiement:
    docker:
      - image: cimg/node:20.8.1
    steps:
      - attach_workspace:
          at: .
      - run: ls -Rl

workflows:
  build_and_deploy:
    jobs:
      - checkoutEtTests
      - integrationFrontend:
          requires:
            - checkoutEtTests
      - deploiement:
          requires:
            - integrationFrontend
